
---
title: "Class 2b"
author: "Shami Delice"
ID number: 101371
date: "16/10/2025"
---

## Control Structures

### If / Else

```{r}
x <- runif(1, 0, 10)
if (x > 3) {
  y <- 10
} else {
  y <- 0
}
y
```

```{r}
# ifelse example
pvalues <- c(.867, 0.0054, 0.0018, 0.1572, 0.0183, 0.5386)
results <- ifelse(pvalues < 0.05, "Significant", "Not significant")
results
```

### For Loops

```{r}
for(i in 1:10) {
  print(i)
}

x <- c("a","b","c","d")
for(i in 1:5) print(x[i])
```

### While Loops

```{r}
count <- 1
while(count < 10) {
  print(count)
  count <- count + 1
}
```

### Break and Next

```{r}
for(i in 1:100) {
  if(i > 20) break
  print(1:i)
}
```

## Functions

```{r}
f <- function(x) x^2
f(4)

f2 <- function(x, y) {
  result <- x^2 + y^2 - 4
  return(result)
}
f2(3, 2)
```

```{r}
# Using args, body, formals, environment
args(f2)
body(f2)
formals(f2)
environment(f2)
```

## Matrices and Apply

```{r}
c <- matrix(runif(12), nrow=3)
c
rowMeans(c)
colMeans(c)
apply(c, 1, sum)
apply(c, 2, sum)
```

```{r}
# Example of lapply
fix_missing <- function(x) {
  x[x == -99] <- NA
  x
}
```

## Titanic Data

```{r}
str(Titanic)
apply(Titanic, c(1,2), sum)
apply(Titanic, c(1,4), sum)
ftable(apply(Titanic, c(1,4,2), sum)[3:4,,])
```

## Creating a Student Dataset and Grading

```{r}
Student <- c("Johnncuti","Angelabakame","Brucewizeye","Alexisaganze",
             "claudeRukundo","JoelKagabo","Maryineza")
Math <- c(600, 412, 358, 495, 512, 410, 522)
Science <- c(95, 99, 80, 82, 75, 89, 77)
English <- c(25, 22, 18, 20, 29, 30, 27)
roster <- data.frame(Student, Math, Science, English, stringsAsFactors=FALSE)

z <- scale(roster[,2:4])
score <- apply(z, 1, mean)
roster <- cbind(roster, score)

y <- quantile(score, c(.8, .6, .4, .2))
roster$grade[score >= y[1]] <- "A"
roster$grade[score < y[1] & score >= y[2]] <- "B"
roster$grade[score < y[2] & score >= y[3]] <- "C"
roster$grade[score < y[3] & score >= y[4]] <- "D"
roster$grade[score < y[4]] <- "F"

roster
```

## Aggregation and Reshaping

```{r}
library(reshape2)

id <- c(1,1,2,2)
time <- c(1,2,1,2)
x1 <- c(5,3,6,2)
x2 <- c(6,5,1,4)
mydata <- data.frame(id, time, x1, x2)
melted <- melt(mydata, id.vars=c("id","time"))
dcast(melted, id ~ variable, fun.aggregate=mean)
```
