---
title: "Class 2a"
author: "Shami Delice"
ID: "101371"
date: "2025-10-17"
output: html_document
---


## COVID-19 Data Analysis

```{r covid-data, echo=TRUE}
# Reading confirmed cases by gender
data1 <- read.table(text="Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 4 6 30 140 67 47 23 39 134 80
2 10 2 29 164 72 81 28 63 211 132", header=TRUE)

barplot(as.matrix(data1), main="Confirmed cases Vs Gender", beside=TRUE, col=c("gold3","red"))
legend("topright", c("Male","Female"), cex=0.5, bty="n", fill=c("gold3","red"))

# COVID-19 tests by gender
data3 <- read.table(text="sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 867 582 1802 12003 3059 9205 5346 7269 5933 3245
2 842 436 1805 11785 3508 10908 4902 7883 5901 4646", header=TRUE)

barplot(as.matrix(data3), main="COVID-19 test Vs Gender", beside=TRUE, col=c("blue","purple"))
legend("topleft", c("Male","Female"), cex=1.3, bty="n", fill=c("blue","purple"))

# Confirmed cases by age categories
data2 <- read.table(text="Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 0 0 1 9 8 7 1 4 11 22
2 11 3 41 242 104 78 44 86 244 147
3 3 5 17 53 27 43 6 12 90 43", header=TRUE)

barplot(as.matrix(data2), main="Confirmed cases Vs Age categories", beside=TRUE, col=c("green","blue","purple"))
legend("topleft", c("Less than 15 years","15-49 years","Above 50"), cex=1.3, bty="n", fill=c("green","blue","purple"))
```

## Time Series of Confirmed Cases and Treatment

```{r time-series, echo=TRUE}
months <- c("Sept_2022","Oct_2022","Nov_2022","Dec_2022","Jan_2023","Feb_2023","Mar_2023","Apr_2023","May_2023","June_2023")
Confirmed_covid <- c(14,8,59,304,139,128,51,102,345,212)
treatment <- c(12,0,26,217,104,57,12,47,23,20)

plot(Confirmed_covid, type="l", pch=21, col="red", ylim=c(0,350), xaxt="n", ylab="Number of patients", main="Confirmed cases Vs treatment")
lines(treatment, col="blue", lty=2)
legend("topleft", legend=c("Received treatment","Confirmed"), cex=0.5, fill=c("blue","red"))
axis(1, at=1:10, labels=months)
```

## Number of COVID-19 Tests

```{r covid-tests, echo=TRUE}
number_of_test <- c(1709, 1018, 3607, 23788, 6567, 20113, 10248, 15152, 11834, 7891)
plot(number_of_test, type="o", col="blue", ylim=c(0,24000), xaxt="n", ylab="Number of Tests", main="COVID-19 Tests")
axis(1, at=1:10, labels=months)
```

## ggplot2 Visualizations

```{r ggplot2, message=FALSE, warning=FALSE}
library(ggplot2)
data(mtcars)

# Barplot of cylinder counts
barplot(table(mtcars$cyl), main="Distribution of Car Cylinder Counts", xlab="Number of cylinders", ylab="Number of cars", horiz=TRUE)

# Scatter plot with base R
plot(mtcars$mpg ~ mtcars$wt, main="Automobile Data", xlab="Weight", ylab="Miles per Gallon", pch=21)

# ggplot2 scatter plot
ggplot(data=mtcars, aes(x=wt, y=mpg)) + geom_point() + labs(title="Automobile Data", x="Weight", y="Miles per Gallon")

# Adding linear regression line
ggplot(data=mtcars, aes(x=wt, y=mpg)) + geom_point(pch=17, color="blue", size=1) +
  geom_smooth(method="lm", color="green") +
  labs(title="Automobile Data with Linear Fit", x="Weight", y="Miles per Gallon")
```

## Grouping and Faceting

```{r faceting, echo=TRUE}
mtcars$am <- factor(mtcars$am, levels=c(0,1), labels=c("Automatic","Manual"))
mtcars$vs <- factor(mtcars$vs, levels=c(0,1), labels=c("V-Engine","Straight Engine"))
mtcars$cyl <- factor(mtcars$cyl)

ggplot(data=mtcars, aes(x=hp, y=mpg, shape=cyl, color=cyl)) +
  geom_point(size=3) +
  facet_grid(vs ~ am) +
  labs(title="Automobile Data by Engine Type", x="Horsepower", y="Miles per Gallon")
```

## Boxplots

```{r boxplot, echo=TRUE}
data(singer, package="lattice")
ggplot(singer, aes(x=voice.part, y=height)) + geom_boxplot()
```

## Data Management Examples

```{r data-management, echo=TRUE}
# cbind and rbind
data2 <- data.frame(x=1:3, y=c("a","b","c"))
cbind(data2, data.frame(z=3:1))
rbind(data2, data.frame(x=10, y="z"))

# BMI calculation
# Read CSV properly
data_class <- read.csv("C:\\Users\\NHIC - Delice\\Downloads\\class_data.csv", header=TRUE)

# Check column classes
str(data_class)

data_class$HEIGHT <- as.numeric(data_class$HEIGHT)
data_class$WEIGHT <- as.numeric(data_class$WEIGHT)

# Calculate BMI
BMI <- round(data_class$WEIGHT / (data_class$HEIGHT / 100)^2, 1)

# View result
head(cbind(data_class, BMI))
summary(BMI)

```

## Leadership Data Example

```{r leadership, echo=TRUE}
manager <- c(1,2,3,4,5)
country <- c("US","US","UK","UK","UK")
gender <- c("M","F","F","M","F")
age <- c(32,45,25,39,99)
q1 <- c(5,3,3,3,2)
q2 <- c(4,5,5,3,2)
q3 <- c(5,2,5,4,1)
q4 <- c(5,5,5,NA,2)
q5 <- c(5,5,2,NA,1)

leadership <- data.frame(manager, country, gender, age, q1, q2, q3, q4, q5)
leadership$age[leadership$age==99] <- NA
leadership$agecat[leadership$age>75] <- "Elder"
leadership$agecat[leadership$age>=35 & leadership$age<=75] <- "MiddleAged"
leadership$agecat[leadership$age<35] <- "Young"

newdata <- na.omit(leadership)
newdata2 <- leadership[order(leadership$age),]
newdata7 <- leadership[gender=="M" & age>30,]
```

## dplyr and nycflights13 Example

```{r dplyr-flights, message=FALSE, warning=FALSE}
library(nycflights13)
library(dplyr)

jan <- filter(flights, month==1)
dec25 <- filter(flights, month==12, day==25)
jan_dec <- filter(flights, month==1 | month==12)
nov_dec <- filter(flights, month %in% c(11,12))

flights2 <- select(flights, year:day, ends_with("delay"), distance, air_time)
flights2 <- mutate(flights2, gain=arr_delay - dep_delay, speed=distance/air_time*60)
head(flights2)
```

